use allowRefresh config in combined schema
mapbender/mapbender-digitizer pull request #108
Opened 2024-02-22 07:51 UTC by frwg

2024-02-22 09:44 UTC, Phocacius approved these changes

2024-02-23 08:52 UTC, astroidex requested changes

2024-02-23 08:52 UTC, astroidex commented on CHANGELOG.md
> +* use allowRefresh of subschemas in combined schema
Plese add link to PR in the changelog

2024-02-23 09:02 UTC, astroidex approved these changes

2024-02-27 09:38 UTC, merged